import assets from "./assets";

const NFTData = [
  {
    id: "01",
    nome: "Giulia",
    cognome: "Marinucci",
    images: assets.n01,
    commenti: [{ id: "1", voto: "0.0", motivazione: "" }],
    punti: 0,
  },
  {
    id: "02",
    nome: "Chiara",
    cognome: "Ruggeri",
    images: assets.n02,
    commenti: [{ id: "1", voto: "0.0", motivazione: "" }],
    punti: 0,
  },
  {
    id: "03",
    nome: "Lucrezia",
    cognome: "Bernazzani",
    images: assets.n03,
    commenti: [{ id: "1", voto: "0.0", motivazione: "" }],
    punti: 0,
  },
  {
    id: "04",
    nome: "Fabiana",
    cognome: "Luciani",
    images: assets.n04,
    commenti: [{ id: "1", voto: "0.0", motivazione: "" }],
    punti: 0,
  },
  {
    id: "05",
    nome: "Sara",
    cognome: "Di Stefano",
    images: assets.n05,
    commenti: [{ id: "1", voto: "0.0", motivazione: "" }],
    punti: 0,
  },
  {
    id: "06",
    nome: "Ludovica",
    cognome: "Rossi",
    images: assets.ludovica,
    commenti: [{ id: "1", voto: "0.0", motivazione: "" }],
    punti: 0,
  },
  {
    id: "07",
    nome: "Irene",
    cognome: "Moretti",
    images: assets.irene,
    commenti: [{ id: "1", voto: "0.0", motivazione: "" }],
    punti: 0,
  },
  {
    id: "08",
    nome: "Andrea",
    cognome: "Cotini",
    images: assets.andrea,
    commenti: [{ id: "1", voto: "0.0", motivazione: "" }],
    punti: 0,
  },
  {
    id: "09",
    nome: "Lollino",
    cognome: "Goglia",
    images: assets.goglia,
    commenti: [{ id: "1", voto: "0.0", motivazione: "" }],
    punti: 0,
  },
  {
    id: "10",
    nome: "Matteo",
    cognome: "Di Mango",
    images: assets.matteo,
    commenti: [{ id: "1", voto: "0.0", motivazione: "" }],
    punti: 0,
  },
  {
    id: "11",
    nome: "Alessandro",
    cognome: "Serafini",
    alias: "Seraf",
    images: assets.seraf,
    commenti: [{ id: "1", voto: "0.0", motivazione: "" }],
    punti: 0,
  },
  {
    id: "12",
    nome: "Lorenzo",
    cognome: "Giare",
    images: assets.lorenzogiare,
    commenti: [{ id: "1", voto: "0.0", motivazione: "" }],
    punti: 0,
  },
  {
    id: "13",
    nome: "Ale",
    cognome: "Agace",
    alias: "Agace",
    images: assets.agace,
    commenti: [{ id: "1", voto: "0.0", motivazione: "" }],
    punti: 0,
  },

  {
    id: "14",
    nome: "Giacomo",
    cognome: "Macchi",
    images: assets.giacomo,
    commenti: [{ id: "1", voto: "0.0", motivazione: "" }],
    punti: 0,
  },
  {
    id: "15",
    nome: "Emanuele",
    cognome: "Carosi",
    images: assets.emanuele,
    commenti: [{ id: "1", voto: "0.0", motivazione: "" }],
    punti: 0,
  },
];

export { NFTData };
